### ISSUE TITLE
Osram GU10 white dim 

### ISSUE THREAD

**Issue by cryd-s** [JohanBendz/com.osram.lightify.zigbee#4]
Hello, i cannot add the Osram GU10 white dim. 

The app add this lights as standard zigbee devise with this specs:

Manufacturer ID: LEDVANCE
Product ID: PAR16 DIM Z3
Devise ID: 257
Profil ID: 260
Networkadress: 0xf0d1b8000010641c

Can u help me to add them because as standard zigbee devise i cannot dim them.

Sorry for bad english i hope u understand me ;)

**Comment by JohanBendz** [comment]
@Crykor90 Can you tune the white on this device or is it just white dim?

**Comment by cryd-s** [comment]
hi they are just dim - no tuneable white
